10seconds_install: Support $HOME with space.

diff --git a/10seconds_install b/10seconds_install
--- a/10seconds_install
+++ b/10seconds_install
@@ -55,11 +55,11 @@ run() {
     latest=$($get http://ftpmirror.gnu.org/parallel |
 		 perl -ne '/.*(parallel-\d{8})/ and print $1."\n"' |
 		 perl -e 'print ((reverse sort <>)[0])')
-    if test \! -e $latest.tar.bz2; then
+    if test \! -e "$latest".tar.bz2; then
 	# Source tar does not exist
-	rm -f $latest.tar.bz2 $latest.tar.bz2.sig
-	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2 > $latest.tar.bz2
-	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2.sig > $latest.tar.bz2.sig
+	rm -f "$latest".tar.bz2 "$latest".tar.bz2.sig
+	$get http://ftpmirror.gnu.org/parallel/"$latest".tar.bz2 > "$latest".tar.bz2
+	$get http://ftpmirror.gnu.org/parallel/"$latest".tar.bz2.sig > "$latest".tar.bz2.sig
     fi
 
     fetch_keys() {
@@ -74,10 +74,10 @@ run() {
 	    else
 		keyserver1=keys.gnupg.net
 		keyserver2=pool.sks-keyservers.net
-		if gpg --keyserver $keyserver1 --recv-key 0xFFFFFFF1 ||
-			gpg --keyserver $keyserver2 --recv-key 0xFFFFFFF1 ; then
-		    if gpg --keyserver $keyserver1 --recv-key 0x88888888 ||
-			    gpg --keyserver $keyserver2 --recv-key 0x88888888; then
+		if gpg --keyserver "$keyserver1" --recv-key 0xFFFFFFF1 ||
+			gpg --keyserver "$keyserver2" --recv-key 0xFFFFFFF1 ; then
+		    if gpg --keyserver "$keyserver1" --recv-key 0x88888888 ||
+			    gpg --keyserver "$keyserver2" --recv-key 0x88888888; then
 			# OK
 			return 0
 		    else
@@ -93,19 +93,19 @@ run() {
 	    fi
 	else
 	    # GnuPG not installed
-  	    echo
-       	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
+	    echo
+	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
 	    return 1
 	fi
     }
 
     # Check signature - in case ftpmirror.gnu.org is compromised
     if fetch_keys; then
-	if gpg --with-fingerprint $latest.tar.bz2.sig 2>&1 |
+	if gpg --with-fingerprint "$latest".tar.bz2.sig 2>&1 |
 	       perl -e 'exit not grep /^Primary key fingerprint: BE9C B493 81DE 3166 A3BC  66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610  7E7B D1AB 4516 8888 8888/, <>'; then
 	    # Source code signed by Ole Tange <ole@tange.dk>
 	    # KeyID FFFFFFF1/88888888
-   	    true
+	    true
 	else
 	    # GnuPG signature failed
 	    echo
@@ -114,57 +114,57 @@ run() {
 	    echo
 	    echo "See http://git.savannah.gnu.org/cgit/parallel.git/tree/README for other installation methods."
 	    exit 1
-     	fi
+	fi
     else
 	# GnuPG not installed or public keys not downloaded
 	echo "This means that if the code has been changed by criminals, you will not discover that!"
 	echo
 	echo "Continue anyway? (y/n)"
-      	read YN </dev/tty
+	read YN </dev/tty
 	if test "$YN" = "n"; then
 	    # Stop
 	    exit 2
 	else
 	    # Continue
 	    true
-      	fi
+	fi
     fi
 
-    bzip2 -dc $latest.tar.bz2 | tar xf -
-    cd $latest || exit 2
+    bzip2 -dc "$latest".tar.bz2 | tar xf -
+    cd "$latest" || exit 2
     if ./configure && make && make install; then
 	echo
-	echo GNU $latest installed globally
+	echo "GNU $latest installed globally"
     else
-	if ./configure --prefix=$HOME && make && make install; then
+	if ./configure --prefix="$HOME" && make && make install; then
 	    echo
-	    echo GNU $latest installed in $HOME/bin
+	    echo "GNU $latest installed in $HOME/bin"
 	else
-	    mkdir -p $HOME/bin/;
-       	    chmod 755 src/*;
-	    cp src/parallel src/env_parallel* src/sem src/sql src/niceload src/parcat $HOME/bin;
+	    mkdir -p "$HOME"/bin/;
+	    chmod 755 src/*;
+	    cp src/parallel src/env_parallel* src/sem src/sql src/niceload src/parcat "$HOME"/bin;
 	    echo
-	    echo GNU $latest copied to $HOME/bin
+	    echo "GNU $latest copied to $HOME/bin"
 	fi
 
 	# Is $HOME/bin already in $PATH?
-	if echo $PATH | grep $HOME/bin >/dev/null; then
+	if echo "$PATH" | grep "$HOME"/bin >/dev/null; then
 	    # $HOME/bin is already in $PATH
 	    true
 	else
 	    # Add $HOME/bin to $PATH for both bash and csh
-	    echo 'PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
-	    echo 'setenv PATH ${PATH}:${HOME}/bin' >> $HOME/.cshrc
-  	fi
+	    echo 'PATH=$PATH:$HOME/bin' >> "$HOME"/.bashrc
+	    echo 'setenv PATH ${PATH}:${HOME}/bin' >> "$HOME"/.cshrc
+	fi
 
 	# Is $HOME/share/man already in $MANPATH?
-	if echo $MANPATH | grep $HOME/share/man >/dev/null; then
+	if echo "$MANPATH" | grep "$HOME"/share/man >/dev/null; then
 	    # $HOME/share/man is already in $MANPATH
 	    true
 	else
 	    # Add $HOME/share/man to $MANPATH for both bash and csh
-	    echo 'MANPATH=$MANPATH:$HOME/share/man' >> $HOME/.bashrc
-	    echo 'setenv MANPATH ${MANPATH}:${HOME}/share/man' >> $HOME/.cshrc
+	    echo 'export MANPATH=$MANPATH:$HOME/share/man' >> "$HOME"/.bashrc
+	    echo 'setenv MANPATH ${MANPATH}:${HOME}/share/man' >> "$HOME"/.cshrc
 	fi
     fi
 }
