Released as 20200422 ('10years')

diff --git a/10seconds_install b/10seconds_install
--- a/10seconds_install
+++ b/10seconds_install
@@ -36,7 +36,7 @@ run() {
     fi
 
     if ! perl -e 1; then
-   	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
+	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
 	exit 1
     fi
 
@@ -45,7 +45,7 @@ run() {
 		 perl -ne '/.*(parallel-\d{8})/ and print $1."\n"' |
 		 perl -e 'print ((reverse sort <>)[0])')
     if test \! -e $latest.tar.bz2; then
- 	# Source tar does not exist
+	# Source tar does not exist
 	rm -f $latest.tar.bz2 $latest.tar.bz2.sig
 	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2 > $latest.tar.bz2
 	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2.sig > $latest.tar.bz2.sig
@@ -56,30 +56,36 @@ run() {
 	    # GnuPG installed
 	    # Setup .gnupg/gpg.conf if not already done
 	    echo | gpg 2>/dev/null >/dev/null
-	    keyserver1=keys.gnupg.net
-	    keyserver2=pool.sks-keyservers.net
-  	    if gpg --keyserver $keyserver1 --recv-key 0xFFFFFFF1 ||
-		    gpg --keyserver $keyserver2 --recv-key 0xFFFFFFF1 ; then
-		if gpg --keyserver $keyserver1 --recv-key 0x88888888 ||
-    			gpg --keyserver $keyserver2 --recv-key 0x88888888; then
-		    # OK
-		    return 0
+	    if gpg --list-keys 0xFFFFFFF1 && gpg --list-keys 0x88888888 ; then
+		echo Keys fetched
+		# OK
+		return 0
+	    else
+		keyserver1=keys.gnupg.net
+		keyserver2=pool.sks-keyservers.net
+		if gpg --keyserver $keyserver1 --recv-key 0xFFFFFFF1 ||
+			gpg --keyserver $keyserver2 --recv-key 0xFFFFFFF1 ; then
+		    if gpg --keyserver $keyserver1 --recv-key 0x88888888 ||
+			    gpg --keyserver $keyserver2 --recv-key 0x88888888; then
+			# OK
+			return 0
+		    else
+			echo
+			echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
+			return 1
+		    fi
 		else
-     		    echo
-		    echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
+		    echo
+		    echo "Cannot fetch keyID 0xFFFFFFF1, so the signature cannot be checked."
 		    return 1
 		fi
-	    else
-		echo
-		echo "Cannot fetch keyID 0xFFFFFFF1, so the signature cannot be checked."
-		return 1
 	    fi
 	else
 	    # GnuPG not installed
 	    echo
 	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
 	    return 1
-       	fi
+	fi
     }
 
     # Check signature - in case ftpmirror.gnu.org is compromised
@@ -96,7 +102,7 @@ run() {
 	    echo "THIS IS BAD AND THE CODE WILL NOT BE INSTALLED."
 	    echo
 	    echo "See http://git.savannah.gnu.org/cgit/parallel.git/tree/README for other installation methods."
-    	    exit 1
+	    exit 1
 	fi
     else
 	# GnuPG not installed or public keys not downloaded
@@ -110,7 +116,7 @@ run() {
 	else
 	    # Continue
 	    true
-     	fi
+	fi
     fi
 
     bzip2 -dc $latest.tar.bz2 | tar xf -
@@ -127,7 +133,7 @@ run() {
 	    chmod 755 src/*;
 	    cp src/parallel src/env_parallel* src/sem src/sql src/niceload src/parcat $HOME/bin;
 	    echo
-      	    echo GNU $latest copied to $HOME/bin
+	    echo GNU $latest copied to $HOME/bin
 	fi
 
 	# Is $HOME/bin already in $PATH?
@@ -138,10 +144,10 @@ run() {
 	    # Add $HOME/bin to $PATH for both bash and csh
 	    echo 'PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
 	    echo 'setenv PATH ${PATH}:${HOME}/bin' >> $HOME/.cshrc
-     	fi
+	fi
 
 	# Is $HOME/share/man already in $MANPATH?
-    	if echo $MANPATH | grep $HOME/share/man >/dev/null; then
+	if echo $MANPATH | grep $HOME/share/man >/dev/null; then
 	    # $HOME/share/man is already in $MANPATH
 	    true
 	else
