parallel: Give better error message if file not found when using --pipepart.

diff --git a/10seconds_install b/10seconds_install
--- a/10seconds_install
+++ b/10seconds_install
@@ -23,18 +23,12 @@
 #    $ bash install.sh
 
 run() {
-    # tail on openindiana must be /usr/xpg4/bin/tail
-    tail=$(echo | tail -n 1 2>/dev/null && echo tail ||
-		      (echo | /usr/xpg4/bin/tail -n 1 && echo /usr/xpg4/bin/tail))
-    # grep on openindiana must be /usr/xpg4/bin/grep
-    grep=$(echo | grep -vE . 2>/dev/null && echo grep ||
-		      (echo | /usr/xpg4/bin/grep -vE . && echo /usr/xpg4/bin/grep))
     # FreeBSD prefers 'fetch', MacOS prefers 'curl', Linux prefers 'wget'
     get=$(
 	(lynx -source /dev/null && echo lynx -source) ||
 	    (fetch -o /dev/null file:///bin/sh && echo fetch -o -) ||
 	    (curl -h >/dev/null && echo curl -L) ||
-       	    (wget -h >/dev/null && echo wget -qO -) ||
+	    (wget -h >/dev/null && echo wget -qO -) ||
 	    echo 'No lynx, wget, curl, fetch: Please inform parallel@gnu.org what you use for downloading URLs' >&2
        )
     if test "$get" = ""; then
@@ -42,17 +36,17 @@ run() {
     fi
 
     if ! perl -e 1; then
-	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
+   	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
 	exit 1
     fi
 
     LANG=C
     latest=$($get http://ftpmirror.gnu.org/parallel |
-		    perl -ne '/.*(parallel-\d{8})/ and print $1."\n"' |
-		    sort | $tail -n1)
+		 perl -ne '/.*(parallel-\d{8})/ and print $1."\n"' |
+		 perl -e 'print ((reverse sort <>)[0])')
     if test \! -e $latest.tar.bz2; then
-	# Source tar does not exist
-       	rm -f $latest.tar.bz2 $latest.tar.bz2.sig
+ 	# Source tar does not exist
+	rm -f $latest.tar.bz2 $latest.tar.bz2.sig
 	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2 > $latest.tar.bz2
 	$get http://ftpmirror.gnu.org/parallel/$latest.tar.bz2.sig > $latest.tar.bz2.sig
     fi
@@ -60,49 +54,49 @@ run() {
     fetch_keys() {
 	if gpg -h 2>/dev/null >/dev/null ; then
 	    # GnuPG installed
-      	    # Setup .gnupg/gpg.conf if not already done
-   	    echo | gpg 2>/dev/null >/dev/null
+	    # Setup .gnupg/gpg.conf if not already done
+	    echo | gpg 2>/dev/null >/dev/null
 	    keyserver1=keys.gnupg.net
 	    keyserver2=pool.sks-keyservers.net
-	    if gpg --keyserver $keyserver1 --recv-key 0xFFFFFFF1 ||
-   		    gpg --keyserver $keyserver2 --recv-key 0xFFFFFFF1 ; then
+  	    if gpg --keyserver $keyserver1 --recv-key 0xFFFFFFF1 ||
+		    gpg --keyserver $keyserver2 --recv-key 0xFFFFFFF1 ; then
 		if gpg --keyserver $keyserver1 --recv-key 0x88888888 ||
-  			gpg --keyserver $keyserver2 --recv-key 0x88888888; then
+    			gpg --keyserver $keyserver2 --recv-key 0x88888888; then
 		    # OK
 		    return 0
 		else
-		    echo
+     		    echo
 		    echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
 		    return 1
 		fi
-  	    else
+	    else
 		echo
 		echo "Cannot fetch keyID 0xFFFFFFF1, so the signature cannot be checked."
 		return 1
 	    fi
 	else
 	    # GnuPG not installed
-  	    echo
+	    echo
 	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
 	    return 1
-	fi
+       	fi
     }
 
     # Check signature - in case ftpmirror.gnu.org is compromised
     if fetch_keys; then
-      	if gpg --with-fingerprint $latest.tar.bz2.sig 2>&1 |
-	       $grep -E '^Primary key fingerprint: BE9C B493 81DE 3166 A3BC  66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610  7E7B D1AB 4516 8888 8888' ; then
-   	    # Source code signed by Ole Tange <ole@tange.dk>
+	if gpg --with-fingerprint $latest.tar.bz2.sig 2>&1 |
+	       perl -e 'exit not grep /^Primary key fingerprint: BE9C B493 81DE 3166 A3BC  66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610  7E7B D1AB 4516 8888 8888/, <>'; then
+	    # Source code signed by Ole Tange <ole@tange.dk>
 	    # KeyID FFFFFFF1/88888888
 	    true
 	else
-    	    # GnuPG signature failed
+	    # GnuPG signature failed
 	    echo
-    	    echo "The signature on $latest.tar.bz2 is wrong. This may indicate that a criminal has changed the code."
+	    echo "The signature on $latest.tar.bz2 is wrong. This may indicate that a criminal has changed the code."
 	    echo "THIS IS BAD AND THE CODE WILL NOT BE INSTALLED."
 	    echo
 	    echo "See http://git.savannah.gnu.org/cgit/parallel.git/tree/README for other installation methods."
-      	    exit 1
+    	    exit 1
 	fi
     else
 	# GnuPG not installed or public keys not downloaded
@@ -111,12 +105,12 @@ run() {
 	echo "Continue anyway? (y/n)"
 	read YN </dev/tty
 	if test "$YN" = "n"; then
-  	    # Stop
-  	    exit 2
-   	else
-  	    # Continue
-  	    true
-	fi
+	    # Stop
+	    exit 2
+	else
+	    # Continue
+	    true
+     	fi
     fi
 
     bzip2 -dc $latest.tar.bz2 | tar xf -
@@ -126,35 +120,35 @@ run() {
 	echo GNU $latest installed globally
     else
 	if ./configure --prefix=$HOME && make && make install; then
-  	    echo
+	    echo
 	    echo GNU $latest installed in $HOME/bin
 	else
 	    mkdir -p $HOME/bin/;
-       	    chmod 755 src/*;
+	    chmod 755 src/*;
 	    cp src/parallel src/env_parallel* src/sem src/sql src/niceload src/parcat $HOME/bin;
 	    echo
-       	    echo GNU $latest copied to $HOME/bin
+      	    echo GNU $latest copied to $HOME/bin
 	fi
 
 	# Is $HOME/bin already in $PATH?
 	if echo $PATH | grep $HOME/bin >/dev/null; then
 	    # $HOME/bin is already in $PATH
 	    true
-      	else
+	else
 	    # Add $HOME/bin to $PATH for both bash and csh
 	    echo 'PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
 	    echo 'setenv PATH ${PATH}:${HOME}/bin' >> $HOME/.cshrc
-	fi
+     	fi
 
 	# Is $HOME/share/man already in $MANPATH?
-	if echo $MANPATH | grep $HOME/share/man >/dev/null; then
+    	if echo $MANPATH | grep $HOME/share/man >/dev/null; then
 	    # $HOME/share/man is already in $MANPATH
 	    true
 	else
 	    # Add $HOME/share/man to $MANPATH for both bash and csh
-   	    echo 'MANPATH=$MANPATH:$HOME/share/man' >> $HOME/.bashrc
-   	    echo 'setenv MANPATH ${MANPATH}:${HOME}/share/man' >> $HOME/.cshrc
-     	fi
+	    echo 'MANPATH=$MANPATH:$HOME/share/man' >> $HOME/.bashrc
+	    echo 'setenv MANPATH ${MANPATH}:${HOME}/share/man' >> $HOME/.cshrc
+	fi
     fi
 }
 
