parset: support for associative arrays in bash, ksh, zsh.

diff --git a/10seconds_install b/10seconds_install
--- a/10seconds_install
+++ b/10seconds_install
@@ -12,7 +12,7 @@ true <<'EOF'
 <p>  You can download and run the script directly by:
 
 <p>  $ (wget -O - pi.dk/3 || lynx -source pi.dk/3 ||
-        curl pi.dk/3/ || fetch -o - http://pi.dk/3) > install.sh
+	curl pi.dk/3/ || fetch -o - http://pi.dk/3) > install.sh
 <br> $ sha1sum install.sh | grep 12345678
 <br> $ md5sum install.sh
 <br> $ sha512sum install.sh
@@ -45,11 +45,11 @@ run() {
 	    echo 'No lynx, wget, curl, fetch: Please inform parallel@gnu.org what you use for downloading URLs' >&2
        )
     if test "$get" = ""; then
- 	exit 1
+	exit 1
     fi
 
     if ! perl -e 1; then
-       	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
+	echo No perl installed. GNU Parallel depends on perl. Install perl and retry.
 	exit 1
     fi
 
@@ -68,46 +68,42 @@ run() {
 	if gpg -h 2>/dev/null >/dev/null ; then
 	    # GnuPG installed
 	    # Setup .gnupg/gpg.conf if not already done
-     	    echo | gpg 2>/dev/null >/dev/null
+	    echo | gpg 2>/dev/null >/dev/null
 	    if gpg --list-keys 0xFFFFFFF1 && gpg --list-keys 0x88888888 ; then
 		echo Keys fetched
 		# OK
 		return 0
 	    else
-		keyserver1=keys.gnupg.net
-		keyserver2=pool.sks-keyservers.net
-		if gpg --keyserver "$keyserver1" --recv-key 0xFFFFFFF1 ||
-			gpg --keyserver "$keyserver2" --recv-key 0xFFFFFFF1 ; then
-		    if gpg --keyserver "$keyserver1" --recv-key 0x88888888 ||
-			    gpg --keyserver "$keyserver2" --recv-key 0x88888888; then
+		keyservers="pgp.surf.nl
+   			    keyserver.bazon.ru
+			    agora.cenditel.gob.ve
+			    pgp.benny-baumann.de"
+		for keyserver in $keyservers ; do
+		    if gpg --keyserver "$keyserver" --recv-key 0xFFFFFFF1 &&
+			    gpg --keyserver "$keyserver" --recv-key 0x88888888 ; then
 			# OK
 			return 0
-		    else
-			echo
-			echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
-			return 1
 		    fi
-		else
-		    echo
-		    echo "Cannot fetch keyID 0xFFFFFFF1, so the signature cannot be checked."
-		    return 1
-		fi
-      	    fi
-	else
+		done
+		echo
+		echo "Cannot fetch keyID 0x88888888, so the signature cannot be checked."
+		return 1
+	    fi
+  	else
 	    # GnuPG not installed
 	    echo
 	    echo "GnuPG (gpg) is not installed so the signature cannot be checked."
-       	    return 1
+	    return 1
 	fi
     }
 
     # Check signature - in case ftpmirror.gnu.org is compromised
     if fetch_keys; then
 	if gpg --with-fingerprint "$latest".tar.bz2.sig 2>&1 |
-	       perl -e 'exit not grep /^Primary key fingerprint: BE9C B493 81DE 3166 A3BC  66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610  7E7B D1AB 4516 8888 8888/, <>'; then
+	       perl -e 'exit not grep /^Primary key fingerprint: BE9C B493 81DE 3166 A3BC..66C1 2C62 29E2 FFFF FFF1|^Primary key fingerprint: CDA0 1A42 08C4 F745 0610..7E7B D1AB 4516 8888 8888/, <>'; then
 	    # Source code signed by Ole Tange <ole@tange.dk>
-    	    # KeyID FFFFFFF1/88888888
-	    true
+	    # KeyID FFFFFFF1/88888888
+     	    true
 	else
 	    # GnuPG signature failed
 	    echo
@@ -118,17 +114,17 @@ run() {
 	    exit 1
 	fi
     else
-   	# GnuPG not installed or public keys not downloaded
+	# GnuPG not installed or public keys not downloaded
 	echo "This means that if the code has been changed by criminals, you will not discover that!"
-	echo
- 	echo "Continue anyway? (y/n)"
+     	echo
+       	echo "Continue anyway? (y/n)"
 	read YN </dev/tty
 	if test "$YN" = "n"; then
 	    # Stop
 	    exit 2
 	else
 	    # Continue
-      	    true
+	    true
 	fi
     fi
 
@@ -152,7 +148,7 @@ run() {
 	# Is $HOME/bin already in $PATH?
 	if echo "$PATH" | grep "$HOME"/bin >/dev/null; then
 	    # $HOME/bin is already in $PATH
-	    true
+       	    true
 	else
 	    # Add $HOME/bin to $PATH for both bash and csh
 	    echo 'PATH=$PATH:$HOME/bin' >> "$HOME"/.bashrc
@@ -167,7 +163,7 @@ run() {
 	    # Add $HOME/share/man to $MANPATH for both bash and csh
 	    echo 'export MANPATH=$MANPATH:$HOME/share/man' >> "$HOME"/.bashrc
 	    echo 'setenv MANPATH ${MANPATH}:${HOME}/share/man' >> "$HOME"/.cshrc
-  	fi
+	fi
     fi
 }
 
